### ISSUE TITLE
Error: object ‘lengths’ is not exported by 'namespace:BiocGenerics'

### ISSUE THREAD

**Issue by ckntav** [ArnaudDroitLab/ef.utils#1]
Salut Eric,

Lors de l'installation du package ef.utils, j'obtiens l'erreur suivante:
<img width="691" alt="Capture d’écran, le 2019-06-20 à 00 23 53" src="https://user-images.githubusercontent.com/36061268/59818400-bd2b0e80-92f1-11e9-82dd-24504eb8f0db.png">

J'ai réinstaller le package car je suis à la version R 3.6 sur mac. C'est un bug récurrent qui est reporter ici: https://bioc-devel.r-project.narkive.com/InbVVSCB/error-object-lengths-is-not-exported-by-namespace-biocgenerics

La solution est: "The fix is to simply remove any explicit import of lengths from the NAMESPACE. "

Pourras-tu faire la modification? Merci d'avance

**Comment by ericfournier2** [comment]
Salut Christophe,

je ne comprends pas. La fonction "lengths" n'est pas utilisée nulle part dans le package, et elle n'est pas importée non plus. Le package s'installe sans erreur ici. Es-tu certain d'avoir la version la plus récente? Et que les dépendences (IE, les paquets installés en local) sont aussi à jour?

-Eric

**Comment by ckntav** [comment]
Après une mise à jour générale des packages, l'installation fonctionne normalement. Merci de ta réponse. Bonne journée,
